### PR TITLE
fix: split modified to improve compatibility with aarch64-darwin systems

### PR DESCRIPTION
**Pull request by itsOnly1Jah**
I decided to try the module on my m1 Mac and got an error while building the flake that the regular expression was invalid

```shell
error: invalid regular expression ''

       at /nix/store/gg1l117a7fx1334n57zhxcb0mg7ndj4c-source/helper/to_lua/default.nix:18:26:

           17|
           18|       upperCaseLetters = split "" "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
             |                          ^
           19|       lowerCaseLetters = split "" "abcdefghijklmnopqrstuvwxyz";
```

I launched `nix repl` on the m1 tried the split manually on the m1 and got the same error
```shell
nix-repl> builtins.split "" "ABCDEFGHIJKLMNOPQRSTUVWXYZ"                          
error: invalid regular expression ''

       at «string»:1:1:

            1| builtins.split "" "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
             | ^
```
However, on my "x86_64-linux" machine, the original function worked fine
```shell
nix-repl> builtins.split "" "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
[ "" [ ... ] "A" [ ... ] "B" [ ... ] "C" [ ... ] "D" [ ... ] "E" [ ... ] "F" [ ... ] "G" [ ... ] "H" [ ... ] "I" [ ... ] "J" [ ... ] "K" [ ... ] "L" [ ... ] "M" [ ... ] "N" [ ... ] "O" [ ... ] "P" [ ... ] "Q" [ ... ] "R" [ ... ] "S" [ ... ] "T" [ ... ] "U" [ ... ] "V" [ ... ] "W" [ ... ] "X" [ ... ] "Y" [ ... ] "Z" [ ... ] "" ]
```

I opted to do a comma-separated list. Although its not as pretty it works on both machines
```shell
nix-repl> builtins.split "," "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z"
[ "A" [ ... ] "B" [ ... ] "C" [ ... ] "D" [ ... ] "E" [ ... ] "F" [ ... ] "G" [ ... ] "H" [ ... ] "I" [ ... ] "J" [ ... ] "K" [ ... ] "L" [ ... ] "M" [ ... ] "N" [ ... ] "O" [ ... ] "P" [ ... ] "Q" [ ... ] "R" [ ... ] "S" [ ... ] "T" [ ... ] "U" [ ... ] "V" [ ... ] "W" [ ... ] "X" [ ... ] "Y" [ ... ] "Z" ]
```

### CODE REVIEW

**Comment by jooooscha** [comment]
Thanks for investigating.

Actually, I never looked at the output of `split` I thought it would only return the letters as a list, so I was a bit surprised by your repl output. Maybe it's not worth the hassle, and we should just add the list manually?

**Comment by itsOnly1Jah** [comment]
> Thanks for investigating.
> 
> Actually, I never looked at the output of `split`. I thought it would only return the letters as a list, so I was a bit surprised by your repl output. Maybe it's not worth the hassle, and we should just add the list manually?

I'm fine with either implementation. Manually creating the list would probably be more reliable if things were to change down the line. Your call.

**Comment by mirkolenz** [comment]
Just FYI, I just came across this bug on my mac as well. I have an intel-based one, so it does affect `x86_64-darwin` as well. Maybe it is connected to the nix version? I am using `2.13.3`.

**Comment by jooooscha** [comment]
At this point, I would just hard-code the letters. I was not aware this would cause such problems 😅

**Comment by mirkolenz** [comment]
It now works as it should on my machine. Thank you!

**Pull request merged**
