### PR TITLE
null-ls builtins

### PR DESCRIPTION
**Pull request by jalil-salame**
I started the process of adding the builtins, and this seems like it will take a while...

I thought of parsing the markdown with a script and adding comments to `servers.nix` like:

```nix
{
  code_actions.statix.packages = [ pkgs.statix ]; # Manually set package
  completion = {
    # luasnip.packages = [ UNKNOWN ];
    spell.packages = [ ]; # Autogenerated: No package required (no command defined)
  };
}
```

I don't know if that is a good idea though, but I would be willing to try if you think it's fine.

### CODE REVIEW

**Comment by jooooscha** [comment]
I don't use null-ls, so I am not sure what the goal is. Could you briefly describe what you are adding? Thanks :)

**Comment by jalil-salame** [comment]
> I don't use null-ls, so I am not sure what the goal is. Could you briefly describe what you are adding? Thanks :)

Null-ls wraps programs to expose an LSP like API to neovim, it comes with a bunch of configurations like lspconfig, this PR tries to add a bunch of them.

Some sources require extra packages; to format nix files with nixpkgs-fmt you need pks.nixpkgs-fmt

Others are built-in to neovim, like spell suggestions.

This PR exposes some built-in sources, but there are hundreds, therefore I gave up and pushed to get some feedback on wether I should try to autogenerate it from the documentation of null-ls.

**Comment by jooooscha** [comment]
Thanks, this clarifies it for me :)

Auto-generating this would be nice if it is possible 😅

**Comment by jalil-salame** [comment]
So... I don't have time to do this, and I don't think it should be done: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

Null-ls is being archived because the maintenance burden is too much for the maintainer, so it will probably start breaking in the future.

**Pull request closed without merging**
